name: Deploy To Production

on:
  push:
    branches:
      - main
env:
  APP_NAME: 'robot-maker'
  APP_ENV: 'prod'
  PG_CONNECTION_STRING: ${{ secrets.PG_CONNECTION_STRING }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GITHUB_ACTOR: ${{ github.actor }}
  GITHUB_SHA: ${{ github.sha }}

defaults:
  run:
    working-directory: ./phase-1a

jobs:
  login:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: login to ghcr
        run: ./scripts.prod.sh login
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Publish Docker image
        run: ./scripts.prod.sh login && ./scripts.prod.sh publish
  migrate:
    needs: publish
    runs-on: ubuntu-latest
    steps:
      - name: deploy
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.15.0
      - run: ./scripts.prod.sh login && ./scripts.prod.sh migrate
  update:
    needs: migrate
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/relay-network/ops
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: update
        uses: actions/checkout@v3
      - run: ./scripts.prod.sh login && ./scripts.prod.sh update