name: Publish docker image

on:
  push:
    branches:
      - master
jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Publish Docker image
        env:
          GITHUB_SHA: ${{ github.sha }}
        run: |
          docker build -f docker/Dockerfile nodejs -t ghcr.io/relay-network/xmtp-bridge:${{ env.GITHUB_SHA }}
          docker push ghcr.io/relay-network/xmtp-bridge:${{ env.GITHUB_SHA }}

